from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    message: str = Field(..., description="The user message to send to the assistant")

class ChatResponse(BaseModel):
    reply: str = Field(..., description="The response reply generated by the assistant")
